import type { Product } from "./types";

export const products: Product[] = [
  {
    id: "sommarklanning",
    title: "Sommarklänning",
    shortDescription: "Luftig och elegant klänning för varma dagar.",
    description: "En vacker sommarklänning i lätt bomull med blommönster. Perfekt för fester, strandpromenader eller vardagsbruk.",
    features: ["100% bomull", "Luftig passform", "Blommönster", "Maskintvättbar"],
    price: 799,
    image: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=640&h=420&fit=crop&crop=center",
  },
  {
    id: "skinny-jeans",
    title: "Skinny Jeans",
    shortDescription: "Slimma jeans som formar kroppen.",
    description: "Högkvalitativa skinny jeans i stretchmaterial som sitter perfekt. Komfortabla för hela dagen och lätta att kombinera.",
    features: ["Stretchmaterial", "Hög midja", "5 fickor", "Slim passform"],
    price: 599,
    image: "https://images.unsplash.com/photo-1542272604-787c3835535d?w=640&h=420&fit=crop&crop=center",
  },
  {
    id: "silkesblus",
    title: "Silkesblus",
    shortDescription: "Elegant blus i mjuk silke.",
    description: "En tidlös silkesblus med knäppning framtill. Perfekt för kontoret eller en romantisk middag.",
    features: ["100% silke", "Knäppning framtill", "Långärmad", "Elegant design"],
    price: 899,
    image: "https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=640&h=420&fit=crop&crop=center",
  },
  {
    id: "sneakers",
    title: "Vita Sneakers",
    shortDescription: "Klassiska vita sneakers för vardag och sport.",
    description: "Bekväma sneakers i vitt läder med gummisula. Perfekta för promenader, träning eller som vardagsskor.",
    features: ["Läderöverkropp", "Gummisula", "Snörning", "Vattentåliga"],
    price: 699,
    image: "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=640&h=420&fit=crop&crop=center",
  },
  {
    id: "bomullstopp",
    title: "Bomullstopp",
    shortDescription: "Bekväm bomullstopp för vardagen.",
    description: "Mjuk och andas bomullstopp med kort ärm. Perfekt för avslappnade dagar eller som basplagg.",
    features: ["100% bomull", "Kort ärm", "Rund halsringning", "Bekväm passform"],
    price: 249,
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=640&h=420&fit=crop&crop=center",
  },
  {
    id: "cardigan",
    title: "Ullcardigan",
    shortDescription: "Varm och mysig cardigan i ull.",
    description: "Elegant cardigan i mjuk ull som håller dig varm under kyliga dagar. Perfekt över en blus eller ensam.",
    features: ["100% ull", "Knäppning framtill", "Långärmad", "Klassisk design"],
    price: 1299,
    image: "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=640&h=420&fit=crop&crop=center",
  },
  {
    id: "pennykjol",
    title: "Pennykjol",
    shortDescription: "Klassisk pennykjol i tweed.",
    description: "Tidlös pennykjol i kvalitativ tweed. Perfekt för kontoret eller fester med en elegant touch.",
    features: ["Tweedmaterial", "Knäppning framtill", "Midikjol", "Figursydd"],
    price: 899,
    image: "https://images.unsplash.com/photo-1583496661160-fb5886a6aaaa?w=640&h=420&fit=crop&crop=center",
  },
  {
    id: "skinnjacka",
    title: "Läderjacka",
    shortDescription: "Stilren läderjacka för alla tillfällen.",
    description: "Klassisk läderjacka i mjukt läder. Ger en tuff look och passar perfekt över många outfits.",
    features: ["Äkta läder", "Blixtlås framtill", "Flera fickor", "Slim passform"],
    price: 1999,
    image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=640&h=420&fit=crop&crop=center",
  },
  {
    id: "sjal",
    title: "Siden Sjal",
    shortDescription: "Elegant siden sjal för extra stil.",
    description: "Ljuvlig siden sjal som kan användas som accessoar till många outfits. Ger en sofistikerad touch.",
    features: ["100% siden", "Storlek 180x90cm", "Fluffig kant", "Flera färger"],
    price: 499,
    image: "https://images.unsplash.com/photo-1601762603332-db5e4b90cc5d?w=640&h=420&fit=crop&crop=center",
  },
  {
    id: "hogklackat",
    title: "Högklackade Pumps",
    shortDescription: "Eleganta högklackade skor för fest.",
    description: "Klassiska högklackade pumps i svart läder. Perfekta för fester, bröllop eller viktiga möten.",
    features: ["Läder", "10cm klack", "Spetsig tå", "Komfortsula"],
    price: 1299,
    image: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=640&h=420&fit=crop&crop=center",
  },
  {
    id: "handvaska",
    title: "Läder Handväska",
    shortDescription: "Elegant läderväska för vardag och fest.",
    description: "Kvalitativ läderväska med justerbart axelband. Tillräckligt stor för det viktigaste men fortfarande elegant.",
    features: ["Äkta läder", "Justerbart band", "Flera fickor", "Vattentålig"],
    price: 1599,
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=640&h=420&fit=crop&crop=center",
  },
  {
    id: "orhangen",
    title: "Guld Örhängen",
    shortDescription: "Eleganta guldörhängen med pärla.",
    description: "Vackra örhängen i 18k guld med små pärlor. Perfekta för vardag eller festliga tillfällen.",
    features: ["18k guld", "Pärldetaljer", "Lätt design", "Nickelfri"],
    price: 799,
    image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=640&h=420&fit=crop&crop=center",
  },
];
