import type { Product } from "./types";

export const products: Product[] = [
  {
    id: "sommarklanning",
    title: "Sommarklänning",
    shortDescription: "Luftig och elegant klänning för varma dagar.",
    description: "En vacker sommarklänning i lätt bomull med blommönster. Perfekt för fester, strandpromenader eller vardagsbruk.",
    features: ["100% bomull", "Luftig passform", "Blommönster", "Maskintvättbar"],
    price: 799,
    image: "https://via.placeholder.com/640x420?text=Sommarklanning",
  },
  {
    id: "skinny-jeans",
    title: "Skinny Jeans",
    shortDescription: "Slimma jeans som formar kroppen.",
    description: "Högkvalitativa skinny jeans i stretchmaterial som sitter perfekt. Komfortabla för hela dagen och lätta att kombinera.",
    features: ["Stretchmaterial", "Hög midja", "5 fickor", "Slim passform"],
    price: 599,
    image: "https://via.placeholder.com/640x420?text=Skinny+Jeans",
  },
  {
    id: "silkesblus",
    title: "Silkesblus",
    shortDescription: "Elegant blus i mjuk silke.",
    description: "En tidlös silkesblus med knäppning framtill. Perfekt för kontoret eller en romantisk middag.",
    features: ["100% silke", "Knäppning framtill", "Långärmad", "Elegant design"],
    price: 899,
    image: "https://via.placeholder.com/640x420?text=Silkesblus",
  },
  {
    id: "sneakers",
    title: "Vita Sneakers",
    shortDescription: "Klassiska vita sneakers för vardag och sport.",
    description: "Bekväma sneakers i vitt läder med gummisula. Perfekta för promenader, träning eller som vardagsskor.",
    features: ["Läderöverkropp", "Gummisula", "Snörning", "Vattentåliga"],
    price: 699,
    image: "https://via.placeholder.com/640x420?text=Vita+Sneakers",
  },
  {
    id: "bomullstopp",
    title: "Bomullstopp",
    shortDescription: "Bekväm bomullstopp för vardagen.",
    description: "Mjuk och andas bomullstopp med kort ärm. Perfekt för avslappnade dagar eller som basplagg.",
    features: ["100% bomull", "Kort ärm", "Rund halsringning", "Bekväm passform"],
    price: 249,
    image: "https://via.placeholder.com/640x420?text=Bomullstopp",
  },
  {
    id: "cardigan",
    title: "Ullcardigan",
    shortDescription: "Varm och mysig cardigan i ull.",
    description: "Elegant cardigan i mjuk ull som håller dig varm under kyliga dagar. Perfekt över en blus eller ensam.",
    features: ["100% ull", "Knäppning framtill", "Långärmad", "Klassisk design"],
    price: 1299,
    image: "https://via.placeholder.com/640x420?text=Ullcardigan",
  },
  {
    id: "pennykjol",
    title: "Pennykjol",
    shortDescription: "Klassisk pennyk jol i tweed.",
    description: "Tidlös pennyk jol i kvalitativ tweed. Perfekt för kontoret eller fester med en elegant touch.",
    features: ["Tweedmaterial", "Knäppning framtill", "Midikjol", "Figursydd"],
    price: 899,
    image: "https://via.placeholder.com/640x420?text=Pennykjol",
  },
  {
    id: "skinnjacka",
    title: "Läderjacka",
    shortDescription: "Stilren läderjacka för alla tillfällen.",
    description: "Klassisk läderjacka i mjukt läder. Ger en tuff look och passar perfekt över många outfits.",
    features: ["Äkta läder", "Blixtlås framtill", "Flera fickor", "Slim passform"],
    price: 1999,
    image: "https://via.placeholder.com/640x420?text=Laderjacka",
  },
  {
    id: "sjal",
    title: "Siden Sjal",
    shortDescription: "Elegant siden sjal för extra stil.",
    description: "Ljuvlig siden sjal som kan användas som accessoar till många outfits. Ger en sofistikerad touch.",
    features: ["100% siden", "Storlek 180x90cm", "Fluffig kant", "Flera färger"],
    price: 499,
    image: "https://via.placeholder.com/640x420?text=Siden+Sjal",
  },
  {
    id: "hogklackat",
    title: "Högklackade Pumps",
    shortDescription: "Eleganta högklackade skor för fest.",
    description: "Klassiska högklackade pumps i svart läder. Perfekta för fester, bröllop eller viktiga möten.",
    features: ["Läder", "10cm klack", "Spetsig tå", "Komfortsula"],
    price: 1299,
    image: "https://via.placeholder.com/640x420?text=Hogklackade+Pumps",
  },
  {
    id: "handvaska",
    title: "Läder Handväska",
    shortDescription: "Elegant läderväska för vardag och fest.",
    description: "Kvalitativ läderväska med justerbart axelband. Tillräckligt stor för det viktigaste men fortfarande elegant.",
    features: ["Äkta läder", "Justerbart band", "Flera fickor", "Vattentålig"],
    price: 1599,
    image: "https://via.placeholder.com/640x420?text=Lader+Handvaska",
  },
  {
    id: "orhangen",
    title: "Guld Örhängen",
    shortDescription: "Eleganta guldörhängen med pärla.",
    description: "Vackra örhängen i 18k guld med små pärlor. Perfekta för vardag eller festliga tillfällen.",
    features: ["18k guld", "Pärldetaljer", "Lätt design", "Nickelfri"],
    price: 799,
    image: "https://via.placeholder.com/640x420?text=Guld+Orhangen",
  },
];
